# Generated by Django 3.0.7 on 2020-08-05 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='about',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='文章摘要'),
            preserve_default=False,
        ),
    ]
