# Generated by Django 3.0.7 on 2020-08-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='about',
            field=models.TextField(max_length=200, verbose_name='文章摘要'),
        ),
    ]
