# Generated by Django 3.0.7 on 2020-07-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='友链名称')),
                ('picture', models.ImageField(blank=True, upload_to='static/link_pictures', verbose_name='友链头像')),
                ('about', models.CharField(max_length=128, verbose_name='友链介绍')),
                ('address', models.CharField(max_length=128, verbose_name='友链地址')),
            ],
            options={
                'verbose_name': '链接',
                'verbose_name_plural': '链接',
            },
        ),
    ]
