# Generated by Django 3.0.7 on 2020-07-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='address',
            field=models.URLField(verbose_name='友链地址'),
        ),
    ]
