# Generated by Django 3.0.7 on 2020-08-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('avatar', models.ImageField(blank=True, upload_to='static/avatar', verbose_name='头像')),
                ('about', models.CharField(max_length=200, verbose_name='介绍')),
                ('url', models.URLField(verbose_name='地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
