# Generated by Django 3.0.8 on 2020-08-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': '链接', 'verbose_name_plural': '链接'},
        ),
        migrations.AlterField(
            model_name='link',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='media/avatar', verbose_name='头像'),
        ),
    ]
