# Generated by Django 3.0.7 on 2020-07-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='url',
        ),
    ]
